### PR TITLE
Update rawpi.py

### PR DESCRIPTION
**Pull request by ROGERSM94**
Replaced the get_matchhistory function, which is now deprecated, with the get_matchlist function

### CODE REVIEW

**Comment by Kruptein** [comment]
Thanks for the input!

I have a lot of free time now so I'll update the rest of the api were needed in the following days as well.

**Comment by ROGERSM94** [comment]
No problem, it was just changed a few days ago and I needed it for a personal project

**Comment by Kruptein** [comment]
If there is something else you could use, be free to suggest (or implement ^^)

**Comment by ROGERSM94** [comment]
Will do!

**Pull request merged**
